name: package-electron-stable

on:
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      package_version: ${{ steps.package-version.outputs.current-version }}
      release_upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2
      - id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: '.'
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: ${{ steps.package-version.outputs.current-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.current-version }}
          release_name: ${{ steps.package-version.outputs.current-version }}
          body: |
            Version: ${{ steps.package-version.outputs.current-version }}
          draft: false
          prerelease: false

  build_windows:
    needs: [create_release]
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - run: npm install --no-optional
      - run: npm run build-prod
      - run: npm run test-ci
      - run: npm run dist-win32

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.release_upload_url }}
          asset_path: ./dist/display-dj-setup.exe
          asset_name: display-dj-setup.exe
          asset_content_type: application/octet-stream

  build_macos:
    needs: [create_release]
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - run: npm install --no-optional
      - run: npm run build-prod
      - run: npm run test-ci
      - run: npm run dist-darwin

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.release_upload_url }}
          asset_path: ./dist/display-dj-darwin.dmg
          asset_name: display-dj-darwin.dmg
          asset_content_type: application/octet-stream

  publish:
    needs: [create_release, build_windows, build_macos]
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - run: npm version --no-git-tag-version patch
      - run: |
          echo "{ \"version\": \"${{ needs.create_release.outputs.package_version }}\" }" > release.json
      - uses: EndBug/add-and-commit@v8
        with:
          message: 'CI / CD - New Release ${{needs.create_release.outputs.package_version}}'

  roll_back:
    if: failure()
    needs: [create_release, build_windows, build_macos]
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: ${{ steps.package-version.outputs.current-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
