name: package-electron-beta

on:
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    outputs:
      package_version: ${{ steps.package-version.outputs.current-version }}
      release_upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2
      - run: npm version --no-git-tag-version patch
      - id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: '.'
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: beta
          release_name: beta
          body: |
            Version: ${{ steps.package-version.outputs.current-version }}
          draft: false
          prerelease: true

  build_windows:
    needs: [create_release]
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - run: npm version --no-git-tag-version patch
      - run: npm ci --no-optional
      - run: npm run build
      - run: npm run test-ci
      - run: npm run dist-win32

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.release_upload_url }}
          asset_path: ./dist/display-dj-win32-x64.zip
          asset_name: display-dj-win32-x64.zip
          asset_content_type: application/octet-stream

  build_darwin: # darwin aka Mac OSX
    needs: [create_release]
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - run: npm version --no-git-tag-version patch
      - run: npm ci --no-optional
      - run: npm run build
      - run: npm run test-ci
      - run: npm run dist-darwin

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.release_upload_url }}
          asset_path: ./dist/display-dj-darwin-x64.zip
          asset_name: display-dj-darwin-x64.zip
          asset_content_type: application/octet-stream

  roll_back:
    if: failure()
    needs: [create_release, build_windows, build_darwin]
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: 'beta'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
